### ISSUE TITLE
this project is alive ? 

### ISSUE THREAD

**Issue by helderjnpinto** [gnosis/safe-demo#2]
I think the documentation on README is wrong about the api, this project is already maintained?

**Comment by rmeissner** [comment]
The project is not up to date with the latest changed.

Changes that should be made are:
- Use latest endpoints
  - Legacy Safe creation is not supported anymore
- Update host (use `io` domain instead of `pm` domain)

Do you encoder any other issues?

**Comment by helderjnpinto** [comment]
I just tested the first endpoint in the docs. Thanks!
